Algoritmo "Condicional Simples par ou impar com vários SES"
//
//
// Informe um número e verifique se ele é par ou impar
Var
// Seção de Declarações das variáveis
  num: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
 Escreva("Informe um número: ")
 Leia(num)

 Se num%2=0 entao
 Escreva("O número é par")
 Fimse

 Se num%2=1 entao
 Escreva("O número é ímpar")
 Fimse

Fimalgoritmo