Algoritmo "Contagem até 10"
// 
//  
// Descrição   :  Imprima na tela os números de 1 a 0, usando a estrutura de
//             repetição REPITA
//
//
//
// Autor(a)    : Maísa Harumi
// Data atual  : 06/02/2023
//

Var
// Seção de Declarações das variáveis 
 num: inteiro

Inicio

num<-1
Repita
      EscrevaL(num)
      num<-num+1
ate(num>10)

EscrevaL("Fim da contagem")

Fimalgoritmo