Algoritmo "Estrutura Repetição Enquanto"
// 
//  
// Descrição   : Contar até 10
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/02/2023
Var
// Seção de Declarações das variáveis 
cont: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...    ]
Cont<-0
Enquanto cont<30 faca
         cont<- cont + 3
         EscrevaL(cont)
Fimenquanto
EscrevaL("Fim do programa!")

Fimalgoritmo