Algoritmo "Hello World"
// 
//  
// Descrição   : "Escreva" para a informação a ser dada ao usuário. Para a próxima informação ser mostrada em outra linha, precisa escrever "EscrevaL" na linha acima.
// Autor(a)    : Maísa Harumi
// Data atual  : 20/01/2023
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    EscrevaL("Hello World!")
    Escreva("Me livrei da maldição")
Fimalgoritmo